'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("315")>  _
        Public Property BalloonPos() As String
            Get
                Return CType(Me("BalloonPos"),String)
            End Get
            Set
                Me("BalloonPos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property BalloonSize() As String
            Get
                Return CType(Me("BalloonSize"),String)
            End Get
            Set
                Me("BalloonSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property BalloonStyle() As String
            Get
                Return CType(Me("BalloonStyle"),String)
            End Get
            Set
                Me("BalloonStyle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.03125")>  _
        Public Property LinP0() As Decimal
            Get
                Return CType(Me("LinP0"),Decimal)
            End Get
            Set
                Me("LinP0") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.03")>  _
        Public Property LinP1() As Decimal
            Get
                Return CType(Me("LinP1"),Decimal)
            End Get
            Set
                Me("LinP1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.01")>  _
        Public Property LinP2() As Decimal
            Get
                Return CType(Me("LinP2"),Decimal)
            End Get
            Set
                Me("LinP2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.005")>  _
        Public Property LinP3() As Decimal
            Get
                Return CType(Me("LinP3"),Decimal)
            End Get
            Set
                Me("LinP3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.001")>  _
        Public Property LinP4() As Decimal
            Get
                Return CType(Me("LinP4"),Decimal)
            End Get
            Set
                Me("LinP4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-0.03125")>  _
        Public Property LinN0() As Decimal
            Get
                Return CType(Me("LinN0"),Decimal)
            End Get
            Set
                Me("LinN0") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-0.03")>  _
        Public Property LinN1() As Decimal
            Get
                Return CType(Me("LinN1"),Decimal)
            End Get
            Set
                Me("LinN1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-0.01")>  _
        Public Property LinN2() As Decimal
            Get
                Return CType(Me("LinN2"),Decimal)
            End Get
            Set
                Me("LinN2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-0.005")>  _
        Public Property LinN3() As Decimal
            Get
                Return CType(Me("LinN3"),Decimal)
            End Get
            Set
                Me("LinN3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-0.001")>  _
        Public Property LinN4() As Decimal
            Get
                Return CType(Me("LinN4"),Decimal)
            End Get
            Set
                Me("LinN4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property AngP0() As Decimal
            Get
                Return CType(Me("AngP0"),Decimal)
            End Get
            Set
                Me("AngP0") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.5")>  _
        Public Property AngP1() As Decimal
            Get
                Return CType(Me("AngP1"),Decimal)
            End Get
            Set
                Me("AngP1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.25")>  _
        Public Property AngP2() As Decimal
            Get
                Return CType(Me("AngP2"),Decimal)
            End Get
            Set
                Me("AngP2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
        Public Property AngN0() As Decimal
            Get
                Return CType(Me("AngN0"),Decimal)
            End Get
            Set
                Me("AngN0") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-0.5")>  _
        Public Property AngN1() As Decimal
            Get
                Return CType(Me("AngN1"),Decimal)
            End Get
            Set
                Me("AngN1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-0.25")>  _
        Public Property AngN2() As Decimal
            Get
                Return CType(Me("AngN2"),Decimal)
            End Get
            Set
                Me("AngN2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Inch")>  _
        Public Property PUoM() As String
            Get
                Return CType(Me("PUoM"),String)
            End Get
            Set
                Me("PUoM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Millimeter")>  _
        Public Property SUoM() As String
            Get
                Return CType(Me("SUoM"),String)
            End Get
            Set
                Me("SUoM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Degrees")>  _
        Public Property AUoM() As String
            Get
                Return CType(Me("AUoM"),String)
            End Get
            Set
                Me("AUoM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.0005")>  _
        Public Property LinP5() As Decimal
            Get
                Return CType(Me("LinP5"),Decimal)
            End Get
            Set
                Me("LinP5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.00025")>  _
        Public Property LinP6() As Decimal
            Get
                Return CType(Me("LinP6"),Decimal)
            End Get
            Set
                Me("LinP6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.000125")>  _
        Public Property LinP7() As Decimal
            Get
                Return CType(Me("LinP7"),Decimal)
            End Get
            Set
                Me("LinP7") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.00001")>  _
        Public Property LinP8() As Decimal
            Get
                Return CType(Me("LinP8"),Decimal)
            End Get
            Set
                Me("LinP8") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-0.0005")>  _
        Public Property LinN5() As Decimal
            Get
                Return CType(Me("LinN5"),Decimal)
            End Get
            Set
                Me("LinN5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-0.00025")>  _
        Public Property LinN6() As Decimal
            Get
                Return CType(Me("LinN6"),Decimal)
            End Get
            Set
                Me("LinN6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-0.000125")>  _
        Public Property LinN7() As Decimal
            Get
                Return CType(Me("LinN7"),Decimal)
            End Get
            Set
                Me("LinN7") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-0.00001")>  _
        Public Property LinN8() As Decimal
            Get
                Return CType(Me("LinN8"),Decimal)
            End Get
            Set
                Me("LinN8") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.1")>  _
        Public Property AngP3() As Decimal
            Get
                Return CType(Me("AngP3"),Decimal)
            End Get
            Set
                Me("AngP3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.05")>  _
        Public Property AngP4() As Decimal
            Get
                Return CType(Me("AngP4"),Decimal)
            End Get
            Set
                Me("AngP4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.025")>  _
        Public Property AngP5() As Decimal
            Get
                Return CType(Me("AngP5"),Decimal)
            End Get
            Set
                Me("AngP5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.0125")>  _
        Public Property AngP6() As Decimal
            Get
                Return CType(Me("AngP6"),Decimal)
            End Get
            Set
                Me("AngP6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.005")>  _
        Public Property AngP7() As Decimal
            Get
                Return CType(Me("AngP7"),Decimal)
            End Get
            Set
                Me("AngP7") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.001")>  _
        Public Property AngP8() As Decimal
            Get
                Return CType(Me("AngP8"),Decimal)
            End Get
            Set
                Me("AngP8") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-0.1")>  _
        Public Property AngN3() As Decimal
            Get
                Return CType(Me("AngN3"),Decimal)
            End Get
            Set
                Me("AngN3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-0.05")>  _
        Public Property AngN4() As Decimal
            Get
                Return CType(Me("AngN4"),Decimal)
            End Get
            Set
                Me("AngN4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-0.025")>  _
        Public Property AngN5() As Decimal
            Get
                Return CType(Me("AngN5"),Decimal)
            End Get
            Set
                Me("AngN5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-0.0125")>  _
        Public Property AngN6() As Decimal
            Get
                Return CType(Me("AngN6"),Decimal)
            End Get
            Set
                Me("AngN6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-0.005")>  _
        Public Property AngN7() As Decimal
            Get
                Return CType(Me("AngN7"),Decimal)
            End Get
            Set
                Me("AngN7") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-0.001")>  _
        Public Property AngN8() As Decimal
            Get
                Return CType(Me("AngN8"),Decimal)
            End Get
            Set
                Me("AngN8") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Inspection.My.MySettings
            Get
                Return Global.Inspection.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
